package org.luakt.lib;

import java.util.function.Function;

// Java or Kotlin Function,
// in fact is a function dynamic generated by JVM
// and will be invoked with InvokeDynamic instruction
public interface LuaJKFunc extends Function<Object[], Object>, LuaFunc {
    // default method of interface is java8 feature
    @Override
    default Object call(Object[] args) {
        return this.apply(args);
    }
}
